/*
 * Generated by STIR. Do not edit by hand.
 */

#include <sifteo/asset.h>

#pragma once

extern Sifteo::AssetGroup Level1Assets;
extern const Sifteo::FlatAssetImage L1Phoneme1;
extern const Sifteo::FlatAssetImage L1Phoneme2;
extern const Sifteo::FlatAssetImage L1Phoneme3;
extern Sifteo::AssetGroup IconAssets;
extern const Sifteo::AssetImage Icon;
extern Sifteo::AssetGroup BootAssets;
extern const Sifteo::AssetImage Bravo;
extern const Sifteo::AssetImage LoadingBg;
extern Sifteo::AssetGroup TestAssets;
extern const Sifteo::AssetImage Title;
extern Sifteo::AssetGroup Level2Assets;
extern const Sifteo::FlatAssetImage L2Phoneme2;
extern const Sifteo::FlatAssetImage L2Phoneme3;
extern const Sifteo::FlatAssetImage L2Phoneme1;
extern Sifteo::AssetGroup Level3Assets;
extern const Sifteo::FlatAssetImage L3Phoneme1;
extern const Sifteo::FlatAssetImage L3Phoneme2;
extern const Sifteo::FlatAssetImage L3Phoneme3;
extern const Sifteo::AssetAudio SampleSound;
extern const Sifteo::AssetAudio L1Sound;
extern const Sifteo::AssetAudio L2Sound;
extern const Sifteo::AssetAudio L3Sound;
