/*
 * Generated by STIR. Do not edit by hand.
 */

#include <sifteo/asset.h>

#pragma once

extern Sifteo::AssetGroup Level2Assets;
extern const Sifteo::AssetImage L2Phoneme1;
extern const Sifteo::AssetImage L2Phoneme2;
extern const Sifteo::AssetImage L2Phoneme3;
extern Sifteo::AssetGroup MenuAssetGrp;
extern const Sifteo::PinnedAssetImage BgTile;
extern const Sifteo::AssetImage IconChroma;
extern const Sifteo::AssetImage Tip1;
extern const Sifteo::AssetImage Footer;
extern const Sifteo::PinnedAssetImage Grid;
extern const Sifteo::AssetImage IconSandwich;
extern const Sifteo::AssetImage LabelEmpty;
extern const Sifteo::AssetImage LabelUser1;
extern const Sifteo::AssetImage Tip0;
extern const Sifteo::AssetImage LabelUser2;
extern Sifteo::AssetGroup BootAssets;
extern const Sifteo::AssetImage Bravo;
extern const Sifteo::AssetImage LoadingBg;
extern const Sifteo::AssetImage Speaker;
extern const Sifteo::AssetImage Title;
extern Sifteo::AssetGroup IconAssets;
extern const Sifteo::AssetImage Icon;
extern Sifteo::AssetGroup Level1Assets;
extern const Sifteo::AssetImage L1Phoneme1;
extern const Sifteo::AssetImage L1Phoneme2;
extern const Sifteo::AssetImage L1Phoneme3;
extern Sifteo::AssetGroup Level3Assets;
extern const Sifteo::AssetImage L3Phoneme1;
extern const Sifteo::AssetImage L3Phoneme2;
extern const Sifteo::AssetImage L3Phoneme3;
extern const Sifteo::AssetAudio L1GoalSound;
extern const Sifteo::AssetAudio L1Sound1;
extern const Sifteo::AssetAudio L1Sound2;
extern const Sifteo::AssetAudio L1Sound3;
extern const Sifteo::AssetAudio L2GoalSound;
extern const Sifteo::AssetAudio L2Sound1;
extern const Sifteo::AssetAudio L2Sound2;
extern const Sifteo::AssetAudio L2Sound3;
extern const Sifteo::AssetAudio L3GoalSound;
extern const Sifteo::AssetAudio L3Sound1;
extern const Sifteo::AssetAudio L3Sound2;
extern const Sifteo::AssetAudio L3Sound3;
