/*
 * Generated by STIR. Do not edit by hand.
 */

#include <sifteo/asset.h>

#pragma once

extern Sifteo::AssetGroup BootAssets;
extern const Sifteo::AssetImage LoadingBg;
extern Sifteo::AssetGroup TestAssets;
extern const Sifteo::AssetImage Title;
extern Sifteo::AssetGroup IconAssets;
extern const Sifteo::AssetImage Icon;
extern const Sifteo::AssetAudio SampleSound;
