# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Sun Mar 10 23:55:23 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName(_fromUtf8("mainWindow"))
        mainWindow.resize(1024, 768)
        self.gameSelector = QtGui.QTabWidget(mainWindow)
        self.gameSelector.setGeometry(QtCore.QRect(10, 10, 1001, 671))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gameSelector.setFont(font)
        self.gameSelector.setObjectName(_fromUtf8("gameSelector"))
        self.phonemeAwarenessTab = QtGui.QWidget()
        self.phonemeAwarenessTab.setObjectName(_fromUtf8("phonemeAwarenessTab"))
        self.verticalSlider = QtGui.QSlider(self.phonemeAwarenessTab)
        self.verticalSlider.setGeometry(QtCore.QRect(10, 20, 41, 581))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.verticalSlider.setFont(font)
        self.verticalSlider.setMinimum(1)
        self.verticalSlider.setMaximum(10)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setInvertedAppearance(True)
        self.verticalSlider.setInvertedControls(False)
        self.verticalSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verticalSlider.setTickInterval(1)
        self.verticalSlider.setObjectName(_fromUtf8("verticalSlider"))
        self.labelLevel = QtGui.QLabel(self.phonemeAwarenessTab)
        self.labelLevel.setGeometry(QtCore.QRect(20, 610, 46, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelLevel.setFont(font)
        self.labelLevel.setObjectName(_fromUtf8("labelLevel"))
        self.labelLevel1 = QtGui.QLabel(self.phonemeAwarenessTab)
        self.labelLevel1.setGeometry(QtCore.QRect(50, 13, 46, 20))
        self.labelLevel1.setObjectName(_fromUtf8("labelLevel1"))
        self.labelLevel2 = QtGui.QLabel(self.phonemeAwarenessTab)
        self.labelLevel2.setGeometry(QtCore.QRect(50, 80, 46, 13))
        self.labelLevel2.setObjectName(_fromUtf8("labelLevel2"))
        self.labelLevel3 = QtGui.QLabel(self.phonemeAwarenessTab)
        self.labelLevel3.setGeometry(QtCore.QRect(50, 140, 46, 21))
        self.labelLevel3.setObjectName(_fromUtf8("labelLevel3"))
        self.labelLevel4 = QtGui.QLabel(self.phonemeAwarenessTab)
        self.labelLevel4.setGeometry(QtCore.QRect(50, 210, 46, 13))
        self.labelLevel4.setObjectName(_fromUtf8("labelLevel4"))
        self.labelLevel5 = QtGui.QLabel(self.phonemeAwarenessTab)
        self.labelLevel5.setGeometry(QtCore.QRect(50, 270, 46, 13))
        self.labelLevel5.setObjectName(_fromUtf8("labelLevel5"))
        self.labelLevel6 = QtGui.QLabel(self.phonemeAwarenessTab)
        self.labelLevel6.setGeometry(QtCore.QRect(50, 330, 46, 21))
        self.labelLevel6.setObjectName(_fromUtf8("labelLevel6"))
        self.labelLevel7 = QtGui.QLabel(self.phonemeAwarenessTab)
        self.labelLevel7.setGeometry(QtCore.QRect(50, 390, 46, 31))
        self.labelLevel7.setObjectName(_fromUtf8("labelLevel7"))
        self.labelLevel8 = QtGui.QLabel(self.phonemeAwarenessTab)
        self.labelLevel8.setGeometry(QtCore.QRect(50, 450, 46, 31))
        self.labelLevel8.setObjectName(_fromUtf8("labelLevel8"))
        self.labelLevel9 = QtGui.QLabel(self.phonemeAwarenessTab)
        self.labelLevel9.setGeometry(QtCore.QRect(50, 520, 46, 21))
        self.labelLevel9.setObjectName(_fromUtf8("labelLevel9"))
        self.labelLevel10 = QtGui.QLabel(self.phonemeAwarenessTab)
        self.labelLevel10.setGeometry(QtCore.QRect(50, 580, 46, 21))
        self.labelLevel10.setObjectName(_fromUtf8("labelLevel10"))
        self.listSets = QtGui.QListWidget(self.phonemeAwarenessTab)
        self.listSets.setGeometry(QtCore.QRect(100, 30, 256, 521))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.listSets.setFont(font)
        self.listSets.setAlternatingRowColors(True)
        self.listSets.setViewMode(QtGui.QListView.ListMode)
        self.listSets.setObjectName(_fromUtf8("listSets"))
        item = QtGui.QListWidgetItem()
        self.listSets.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listSets.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listSets.addItem(item)
        self.btnAddSet = QtGui.QPushButton(self.phonemeAwarenessTab)
        self.btnAddSet.setGeometry(QtCore.QRect(310, 560, 41, 41))
        self.btnAddSet.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("plus.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAddSet.setIcon(icon)
        self.btnAddSet.setIconSize(QtCore.QSize(32, 32))
        self.btnAddSet.setObjectName(_fromUtf8("btnAddSet"))
        self.btnRemoveSet = QtGui.QPushButton(self.phonemeAwarenessTab)
        self.btnRemoveSet.setGeometry(QtCore.QRect(260, 560, 41, 41))
        self.btnRemoveSet.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("minus.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRemoveSet.setIcon(icon1)
        self.btnRemoveSet.setIconSize(QtCore.QSize(32, 32))
        self.btnRemoveSet.setObjectName(_fromUtf8("btnRemoveSet"))
        self.frame = QtGui.QFrame(self.phonemeAwarenessTab)
        self.frame.setGeometry(QtCore.QRect(380, 30, 581, 571))
        self.frame.setFrameShape(QtGui.QFrame.Panel)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setLineWidth(2)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.goalGroup = QtGui.QGroupBox(self.frame)
        self.goalGroup.setGeometry(QtCore.QRect(10, 10, 561, 161))
        self.goalGroup.setObjectName(_fromUtf8("goalGroup"))
        self.imgGoal = QtGui.QLabel(self.goalGroup)
        self.imgGoal.setGeometry(QtCore.QRect(20, 30, 121, 121))
        self.imgGoal.setFrameShape(QtGui.QFrame.Panel)
        self.imgGoal.setFrameShadow(QtGui.QFrame.Raised)
        self.imgGoal.setText(_fromUtf8(""))
        self.imgGoal.setScaledContents(True)
        self.imgGoal.setObjectName(_fromUtf8("imgGoal"))
        self.btnLoadGoalImage = QtGui.QPushButton(self.goalGroup)
        self.btnLoadGoalImage.setGeometry(QtCore.QRect(160, 30, 121, 51))
        self.btnLoadGoalImage.setObjectName(_fromUtf8("btnLoadGoalImage"))
        self.btnLoadGoalSound = QtGui.QPushButton(self.goalGroup)
        self.btnLoadGoalSound.setGeometry(QtCore.QRect(160, 90, 121, 51))
        self.btnLoadGoalSound.setObjectName(_fromUtf8("btnLoadGoalSound"))
        self.lblGoalImagePath = QtGui.QLabel(self.goalGroup)
        self.lblGoalImagePath.setGeometry(QtCore.QRect(290, 30, 261, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(10)
        self.lblGoalImagePath.setFont(font)
        self.lblGoalImagePath.setFrameShape(QtGui.QFrame.Panel)
        self.lblGoalImagePath.setFrameShadow(QtGui.QFrame.Raised)
        self.lblGoalImagePath.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGoalImagePath.setWordWrap(True)
        self.lblGoalImagePath.setObjectName(_fromUtf8("lblGoalImagePath"))
        self.lblGoalSoundPath = QtGui.QLabel(self.goalGroup)
        self.lblGoalSoundPath.setGeometry(QtCore.QRect(290, 90, 261, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(10)
        self.lblGoalSoundPath.setFont(font)
        self.lblGoalSoundPath.setFrameShape(QtGui.QFrame.Panel)
        self.lblGoalSoundPath.setFrameShadow(QtGui.QFrame.Raised)
        self.lblGoalSoundPath.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGoalSoundPath.setWordWrap(True)
        self.lblGoalSoundPath.setObjectName(_fromUtf8("lblGoalSoundPath"))
        self.distractorGroup = QtGui.QGroupBox(self.frame)
        self.distractorGroup.setGeometry(QtCore.QRect(10, 180, 561, 381))
        self.distractorGroup.setObjectName(_fromUtf8("distractorGroup"))
        self.listDistractors = QtGui.QListWidget(self.distractorGroup)
        self.listDistractors.setGeometry(QtCore.QRect(20, 30, 256, 301))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.listDistractors.setFont(font)
        self.listDistractors.setAlternatingRowColors(True)
        self.listDistractors.setViewMode(QtGui.QListView.ListMode)
        self.listDistractors.setObjectName(_fromUtf8("listDistractors"))
        item = QtGui.QListWidgetItem()
        self.listDistractors.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listDistractors.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listDistractors.addItem(item)
        self.btnAddDistractor = QtGui.QPushButton(self.distractorGroup)
        self.btnAddDistractor.setGeometry(QtCore.QRect(240, 340, 31, 31))
        self.btnAddDistractor.setText(_fromUtf8(""))
        self.btnAddDistractor.setIcon(icon)
        self.btnAddDistractor.setIconSize(QtCore.QSize(24, 24))
        self.btnAddDistractor.setObjectName(_fromUtf8("btnAddDistractor"))
        self.btnRemoveDistractor = QtGui.QPushButton(self.distractorGroup)
        self.btnRemoveDistractor.setGeometry(QtCore.QRect(200, 340, 31, 31))
        self.btnRemoveDistractor.setText(_fromUtf8(""))
        self.btnRemoveDistractor.setIcon(icon1)
        self.btnRemoveDistractor.setIconSize(QtCore.QSize(24, 24))
        self.btnRemoveDistractor.setObjectName(_fromUtf8("btnRemoveDistractor"))
        self.imgDistractor = QtGui.QLabel(self.distractorGroup)
        self.imgDistractor.setGeometry(QtCore.QRect(350, 20, 151, 151))
        self.imgDistractor.setFrameShape(QtGui.QFrame.Panel)
        self.imgDistractor.setFrameShadow(QtGui.QFrame.Raised)
        self.imgDistractor.setText(_fromUtf8(""))
        self.imgDistractor.setScaledContents(True)
        self.imgDistractor.setObjectName(_fromUtf8("imgDistractor"))
        self.lblDistractorImagePath = QtGui.QLabel(self.distractorGroup)
        self.lblDistractorImagePath.setGeometry(QtCore.QRect(300, 220, 251, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(10)
        self.lblDistractorImagePath.setFont(font)
        self.lblDistractorImagePath.setFrameShape(QtGui.QFrame.Panel)
        self.lblDistractorImagePath.setFrameShadow(QtGui.QFrame.Raised)
        self.lblDistractorImagePath.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDistractorImagePath.setWordWrap(True)
        self.lblDistractorImagePath.setObjectName(_fromUtf8("lblDistractorImagePath"))
        self.btnLoadDistractorImage = QtGui.QPushButton(self.distractorGroup)
        self.btnLoadDistractorImage.setGeometry(QtCore.QRect(340, 180, 171, 31))
        self.btnLoadDistractorImage.setObjectName(_fromUtf8("btnLoadDistractorImage"))
        self.lblDistractorSoundPath = QtGui.QLabel(self.distractorGroup)
        self.lblDistractorSoundPath.setGeometry(QtCore.QRect(300, 320, 251, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(10)
        self.lblDistractorSoundPath.setFont(font)
        self.lblDistractorSoundPath.setFrameShape(QtGui.QFrame.Panel)
        self.lblDistractorSoundPath.setFrameShadow(QtGui.QFrame.Raised)
        self.lblDistractorSoundPath.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDistractorSoundPath.setWordWrap(True)
        self.lblDistractorSoundPath.setObjectName(_fromUtf8("lblDistractorSoundPath"))
        self.btnLoadDistractorSound = QtGui.QPushButton(self.distractorGroup)
        self.btnLoadDistractorSound.setGeometry(QtCore.QRect(340, 280, 171, 31))
        self.btnLoadDistractorSound.setObjectName(_fromUtf8("btnLoadDistractorSound"))
        self.gameSelector.addTab(self.phonemeAwarenessTab, _fromUtf8(""))
        self.dividedWordTab = QtGui.QWidget()
        self.dividedWordTab.setObjectName(_fromUtf8("dividedWordTab"))
        self.gameSelector.addTab(self.dividedWordTab, _fromUtf8(""))
        self.workingMemoryTab = QtGui.QWidget()
        self.workingMemoryTab.setObjectName(_fromUtf8("workingMemoryTab"))
        self.gameSelector.addTab(self.workingMemoryTab, _fromUtf8(""))
        self.btnSave = QtGui.QPushButton(mainWindow)
        self.btnSave.setGeometry(QtCore.QRect(180, 700, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btnSave.setFont(font)
        self.btnSave.setObjectName(_fromUtf8("btnSave"))
        self.btnLoad = QtGui.QPushButton(mainWindow)
        self.btnLoad.setGeometry(QtCore.QRect(640, 700, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btnLoad.setFont(font)
        self.btnLoad.setObjectName(_fromUtf8("btnLoad"))

        self.retranslateUi(mainWindow)
        self.gameSelector.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(QtGui.QApplication.translate("mainWindow", "Sifteo Game Customization", None, QtGui.QApplication.UnicodeUTF8))
        self.labelLevel.setText(QtGui.QApplication.translate("mainWindow", "Level", None, QtGui.QApplication.UnicodeUTF8))
        self.labelLevel1.setText(QtGui.QApplication.translate("mainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.labelLevel2.setText(QtGui.QApplication.translate("mainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.labelLevel3.setText(QtGui.QApplication.translate("mainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.labelLevel4.setText(QtGui.QApplication.translate("mainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.labelLevel5.setText(QtGui.QApplication.translate("mainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.labelLevel6.setText(QtGui.QApplication.translate("mainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.labelLevel7.setText(QtGui.QApplication.translate("mainWindow", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.labelLevel8.setText(QtGui.QApplication.translate("mainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.labelLevel9.setText(QtGui.QApplication.translate("mainWindow", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.labelLevel10.setText(QtGui.QApplication.translate("mainWindow", "10", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.listSets.isSortingEnabled()
        self.listSets.setSortingEnabled(False)
        item = self.listSets.item(0)
        item.setText(QtGui.QApplication.translate("mainWindow", "Set 1", None, QtGui.QApplication.UnicodeUTF8))
        item = self.listSets.item(1)
        item.setText(QtGui.QApplication.translate("mainWindow", "Set 2", None, QtGui.QApplication.UnicodeUTF8))
        item = self.listSets.item(2)
        item.setText(QtGui.QApplication.translate("mainWindow", "Set 3", None, QtGui.QApplication.UnicodeUTF8))
        self.listSets.setSortingEnabled(__sortingEnabled)
        self.goalGroup.setTitle(QtGui.QApplication.translate("mainWindow", "Goal Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLoadGoalImage.setText(QtGui.QApplication.translate("mainWindow", "Load Image", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLoadGoalSound.setText(QtGui.QApplication.translate("mainWindow", "Load Sound", None, QtGui.QApplication.UnicodeUTF8))
        self.lblGoalImagePath.setText(QtGui.QApplication.translate("mainWindow", "<no file>", None, QtGui.QApplication.UnicodeUTF8))
        self.lblGoalSoundPath.setText(QtGui.QApplication.translate("mainWindow", "<no file>", None, QtGui.QApplication.UnicodeUTF8))
        self.distractorGroup.setTitle(QtGui.QApplication.translate("mainWindow", "Distractor Settings", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.listDistractors.isSortingEnabled()
        self.listDistractors.setSortingEnabled(False)
        item = self.listDistractors.item(0)
        item.setText(QtGui.QApplication.translate("mainWindow", "Distractor 1", None, QtGui.QApplication.UnicodeUTF8))
        item = self.listDistractors.item(1)
        item.setText(QtGui.QApplication.translate("mainWindow", "Distractor 2", None, QtGui.QApplication.UnicodeUTF8))
        item = self.listDistractors.item(2)
        item.setText(QtGui.QApplication.translate("mainWindow", "Distractor 3", None, QtGui.QApplication.UnicodeUTF8))
        self.listDistractors.setSortingEnabled(__sortingEnabled)
        self.lblDistractorImagePath.setText(QtGui.QApplication.translate("mainWindow", "<no file>", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLoadDistractorImage.setText(QtGui.QApplication.translate("mainWindow", "Load Image", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDistractorSoundPath.setText(QtGui.QApplication.translate("mainWindow", "<no file>", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLoadDistractorSound.setText(QtGui.QApplication.translate("mainWindow", "Load Sound", None, QtGui.QApplication.UnicodeUTF8))
        self.gameSelector.setTabText(self.gameSelector.indexOf(self.phonemeAwarenessTab), QtGui.QApplication.translate("mainWindow", "Phoneme Awareness", None, QtGui.QApplication.UnicodeUTF8))
        self.gameSelector.setTabText(self.gameSelector.indexOf(self.dividedWordTab), QtGui.QApplication.translate("mainWindow", "Divided Words", None, QtGui.QApplication.UnicodeUTF8))
        self.gameSelector.setTabText(self.gameSelector.indexOf(self.workingMemoryTab), QtGui.QApplication.translate("mainWindow", "Working Memory", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSave.setText(QtGui.QApplication.translate("mainWindow", "Save Settings File", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLoad.setText(QtGui.QApplication.translate("mainWindow", "Load Settings File", None, QtGui.QApplication.UnicodeUTF8))

