# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sounds.ui'
#
# Created: Wed Mar 20 21:27:50 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(536, 400)
        self.soundsGroup = QtGui.QGroupBox(Dialog)
        self.soundsGroup.setEnabled(True)
        self.soundsGroup.setGeometry(QtCore.QRect(10, 10, 511, 341))
        self.soundsGroup.setObjectName(_fromUtf8("soundsGroup"))
        self.btnA = QtGui.QPushButton(self.soundsGroup)
        self.btnA.setGeometry(QtCore.QRect(10, 30, 31, 27))
        self.btnA.setAcceptDrops(False)
        self.btnA.setCheckable(True)
        self.btnA.setChecked(False)
        self.btnA.setAutoDefault(True)
        self.btnA.setDefault(False)
        self.btnA.setFlat(False)
        self.btnA.setObjectName(_fromUtf8("btnA"))
        self.btnO = QtGui.QPushButton(self.soundsGroup)
        self.btnO.setGeometry(QtCore.QRect(40, 30, 31, 27))
        self.btnO.setAcceptDrops(False)
        self.btnO.setCheckable(True)
        self.btnO.setChecked(False)
        self.btnO.setAutoDefault(True)
        self.btnO.setDefault(False)
        self.btnO.setFlat(False)
        self.btnO.setObjectName(_fromUtf8("btnO"))
        self.btnEU = QtGui.QPushButton(self.soundsGroup)
        self.btnEU.setGeometry(QtCore.QRect(70, 30, 31, 27))
        self.btnEU.setAcceptDrops(False)
        self.btnEU.setCheckable(True)
        self.btnEU.setChecked(False)
        self.btnEU.setAutoDefault(True)
        self.btnEU.setDefault(False)
        self.btnEU.setFlat(False)
        self.btnEU.setObjectName(_fromUtf8("btnEU"))
        self.btnE_grave = QtGui.QPushButton(self.soundsGroup)
        self.btnE_grave.setGeometry(QtCore.QRect(100, 30, 31, 27))
        self.btnE_grave.setAcceptDrops(False)
        self.btnE_grave.setCheckable(True)
        self.btnE_grave.setChecked(False)
        self.btnE_grave.setAutoDefault(True)
        self.btnE_grave.setDefault(False)
        self.btnE_grave.setFlat(False)
        self.btnE_grave.setObjectName(_fromUtf8("btnE_grave"))
        self.btnE_acute = QtGui.QPushButton(self.soundsGroup)
        self.btnE_acute.setGeometry(QtCore.QRect(140, 70, 31, 27))
        self.btnE_acute.setAcceptDrops(False)
        self.btnE_acute.setCheckable(True)
        self.btnE_acute.setChecked(False)
        self.btnE_acute.setAutoDefault(True)
        self.btnE_acute.setDefault(False)
        self.btnE_acute.setFlat(False)
        self.btnE_acute.setObjectName(_fromUtf8("btnE_acute"))
        self.btnE = QtGui.QPushButton(self.soundsGroup)
        self.btnE.setGeometry(QtCore.QRect(140, 30, 31, 27))
        self.btnE.setAcceptDrops(False)
        self.btnE.setCheckable(True)
        self.btnE.setChecked(False)
        self.btnE.setAutoDefault(True)
        self.btnE.setDefault(False)
        self.btnE.setFlat(False)
        self.btnE.setObjectName(_fromUtf8("btnE"))
        self.btnI = QtGui.QPushButton(self.soundsGroup)
        self.btnI.setGeometry(QtCore.QRect(180, 30, 41, 27))
        self.btnI.setAcceptDrops(False)
        self.btnI.setCheckable(True)
        self.btnI.setChecked(False)
        self.btnI.setAutoDefault(True)
        self.btnI.setDefault(False)
        self.btnI.setFlat(False)
        self.btnI.setObjectName(_fromUtf8("btnI"))
        self.btnU = QtGui.QPushButton(self.soundsGroup)
        self.btnU.setGeometry(QtCore.QRect(220, 30, 31, 27))
        self.btnU.setAcceptDrops(False)
        self.btnU.setCheckable(True)
        self.btnU.setChecked(False)
        self.btnU.setAutoDefault(True)
        self.btnU.setDefault(False)
        self.btnU.setFlat(False)
        self.btnU.setObjectName(_fromUtf8("btnU"))
        self.btnOU = QtGui.QPushButton(self.soundsGroup)
        self.btnOU.setGeometry(QtCore.QRect(250, 30, 41, 27))
        self.btnOU.setAcceptDrops(False)
        self.btnOU.setCheckable(True)
        self.btnOU.setChecked(False)
        self.btnOU.setAutoDefault(True)
        self.btnOU.setDefault(False)
        self.btnOU.setFlat(False)
        self.btnOU.setObjectName(_fromUtf8("btnOU"))
        self.btnAN = QtGui.QPushButton(self.soundsGroup)
        self.btnAN.setGeometry(QtCore.QRect(10, 70, 31, 27))
        self.btnAN.setAcceptDrops(False)
        self.btnAN.setCheckable(True)
        self.btnAN.setChecked(False)
        self.btnAN.setAutoDefault(True)
        self.btnAN.setDefault(False)
        self.btnAN.setFlat(False)
        self.btnAN.setObjectName(_fromUtf8("btnAN"))
        self.btnON = QtGui.QPushButton(self.soundsGroup)
        self.btnON.setGeometry(QtCore.QRect(40, 70, 31, 27))
        self.btnON.setAcceptDrops(False)
        self.btnON.setCheckable(True)
        self.btnON.setChecked(False)
        self.btnON.setAutoDefault(True)
        self.btnON.setDefault(False)
        self.btnON.setFlat(False)
        self.btnON.setObjectName(_fromUtf8("btnON"))
        self.btnUN = QtGui.QPushButton(self.soundsGroup)
        self.btnUN.setGeometry(QtCore.QRect(70, 70, 31, 27))
        self.btnUN.setAcceptDrops(False)
        self.btnUN.setCheckable(True)
        self.btnUN.setChecked(False)
        self.btnUN.setAutoDefault(True)
        self.btnUN.setDefault(False)
        self.btnUN.setFlat(False)
        self.btnUN.setObjectName(_fromUtf8("btnUN"))
        self.btnIN = QtGui.QPushButton(self.soundsGroup)
        self.btnIN.setGeometry(QtCore.QRect(100, 70, 31, 27))
        self.btnIN.setAcceptDrops(False)
        self.btnIN.setCheckable(True)
        self.btnIN.setChecked(False)
        self.btnIN.setAutoDefault(True)
        self.btnIN.setDefault(False)
        self.btnIN.setFlat(False)
        self.btnIN.setObjectName(_fromUtf8("btnIN"))
        self.btnILL = QtGui.QPushButton(self.soundsGroup)
        self.btnILL.setGeometry(QtCore.QRect(180, 70, 41, 27))
        self.btnILL.setAcceptDrops(False)
        self.btnILL.setCheckable(True)
        self.btnILL.setChecked(False)
        self.btnILL.setAutoDefault(True)
        self.btnILL.setDefault(False)
        self.btnILL.setFlat(False)
        self.btnILL.setObjectName(_fromUtf8("btnILL"))
        self.btnUI = QtGui.QPushButton(self.soundsGroup)
        self.btnUI.setGeometry(QtCore.QRect(220, 70, 31, 27))
        self.btnUI.setAcceptDrops(False)
        self.btnUI.setCheckable(True)
        self.btnUI.setChecked(False)
        self.btnUI.setAutoDefault(True)
        self.btnUI.setDefault(False)
        self.btnUI.setFlat(False)
        self.btnUI.setObjectName(_fromUtf8("btnUI"))
        self.btnOI = QtGui.QPushButton(self.soundsGroup)
        self.btnOI.setGeometry(QtCore.QRect(250, 70, 41, 27))
        self.btnOI.setAcceptDrops(False)
        self.btnOI.setCheckable(True)
        self.btnOI.setChecked(False)
        self.btnOI.setAutoDefault(True)
        self.btnOI.setDefault(False)
        self.btnOI.setFlat(False)
        self.btnOI.setObjectName(_fromUtf8("btnOI"))
        self.btnP = QtGui.QPushButton(self.soundsGroup)
        self.btnP.setGeometry(QtCore.QRect(10, 110, 31, 27))
        self.btnP.setAcceptDrops(False)
        self.btnP.setCheckable(True)
        self.btnP.setChecked(False)
        self.btnP.setAutoDefault(True)
        self.btnP.setDefault(False)
        self.btnP.setFlat(False)
        self.btnP.setObjectName(_fromUtf8("btnP"))
        self.btnB = QtGui.QPushButton(self.soundsGroup)
        self.btnB.setGeometry(QtCore.QRect(40, 110, 31, 27))
        self.btnB.setAcceptDrops(False)
        self.btnB.setCheckable(True)
        self.btnB.setChecked(False)
        self.btnB.setAutoDefault(True)
        self.btnB.setDefault(False)
        self.btnB.setFlat(False)
        self.btnB.setObjectName(_fromUtf8("btnB"))
        self.btnF = QtGui.QPushButton(self.soundsGroup)
        self.btnF.setGeometry(QtCore.QRect(70, 110, 31, 27))
        self.btnF.setAcceptDrops(False)
        self.btnF.setCheckable(True)
        self.btnF.setChecked(False)
        self.btnF.setAutoDefault(True)
        self.btnF.setDefault(False)
        self.btnF.setFlat(False)
        self.btnF.setObjectName(_fromUtf8("btnF"))
        self.btnV = QtGui.QPushButton(self.soundsGroup)
        self.btnV.setGeometry(QtCore.QRect(110, 110, 31, 27))
        self.btnV.setAcceptDrops(False)
        self.btnV.setCheckable(True)
        self.btnV.setChecked(False)
        self.btnV.setAutoDefault(True)
        self.btnV.setDefault(False)
        self.btnV.setFlat(False)
        self.btnV.setObjectName(_fromUtf8("btnV"))
        self.btnM = QtGui.QPushButton(self.soundsGroup)
        self.btnM.setGeometry(QtCore.QRect(140, 110, 31, 27))
        self.btnM.setAcceptDrops(False)
        self.btnM.setCheckable(True)
        self.btnM.setChecked(False)
        self.btnM.setAutoDefault(True)
        self.btnM.setDefault(False)
        self.btnM.setFlat(False)
        self.btnM.setObjectName(_fromUtf8("btnM"))
        self.btnR = QtGui.QPushButton(self.soundsGroup)
        self.btnR.setGeometry(QtCore.QRect(170, 110, 31, 27))
        self.btnR.setAcceptDrops(False)
        self.btnR.setCheckable(True)
        self.btnR.setChecked(False)
        self.btnR.setAutoDefault(True)
        self.btnR.setDefault(False)
        self.btnR.setFlat(False)
        self.btnR.setObjectName(_fromUtf8("btnR"))
        self.btnT = QtGui.QPushButton(self.soundsGroup)
        self.btnT.setGeometry(QtCore.QRect(10, 150, 31, 27))
        self.btnT.setAcceptDrops(False)
        self.btnT.setCheckable(True)
        self.btnT.setChecked(False)
        self.btnT.setAutoDefault(True)
        self.btnT.setDefault(False)
        self.btnT.setFlat(False)
        self.btnT.setObjectName(_fromUtf8("btnT"))
        self.btnD = QtGui.QPushButton(self.soundsGroup)
        self.btnD.setGeometry(QtCore.QRect(40, 150, 31, 27))
        self.btnD.setAcceptDrops(False)
        self.btnD.setCheckable(True)
        self.btnD.setChecked(False)
        self.btnD.setAutoDefault(True)
        self.btnD.setDefault(False)
        self.btnD.setFlat(False)
        self.btnD.setObjectName(_fromUtf8("btnD"))
        self.btnS = QtGui.QPushButton(self.soundsGroup)
        self.btnS.setGeometry(QtCore.QRect(70, 150, 31, 27))
        self.btnS.setAcceptDrops(False)
        self.btnS.setCheckable(True)
        self.btnS.setChecked(False)
        self.btnS.setAutoDefault(True)
        self.btnS.setDefault(False)
        self.btnS.setFlat(False)
        self.btnS.setObjectName(_fromUtf8("btnS"))
        self.btnZ = QtGui.QPushButton(self.soundsGroup)
        self.btnZ.setGeometry(QtCore.QRect(110, 150, 31, 27))
        self.btnZ.setAcceptDrops(False)
        self.btnZ.setCheckable(True)
        self.btnZ.setChecked(False)
        self.btnZ.setAutoDefault(True)
        self.btnZ.setDefault(False)
        self.btnZ.setFlat(False)
        self.btnZ.setObjectName(_fromUtf8("btnZ"))
        self.btnN = QtGui.QPushButton(self.soundsGroup)
        self.btnN.setGeometry(QtCore.QRect(140, 150, 31, 27))
        self.btnN.setAcceptDrops(False)
        self.btnN.setCheckable(True)
        self.btnN.setChecked(False)
        self.btnN.setAutoDefault(True)
        self.btnN.setDefault(False)
        self.btnN.setFlat(False)
        self.btnN.setObjectName(_fromUtf8("btnN"))
        self.btnL = QtGui.QPushButton(self.soundsGroup)
        self.btnL.setGeometry(QtCore.QRect(170, 150, 31, 27))
        self.btnL.setAcceptDrops(False)
        self.btnL.setCheckable(True)
        self.btnL.setChecked(False)
        self.btnL.setAutoDefault(True)
        self.btnL.setDefault(False)
        self.btnL.setFlat(False)
        self.btnL.setObjectName(_fromUtf8("btnL"))
        self.btnK = QtGui.QPushButton(self.soundsGroup)
        self.btnK.setGeometry(QtCore.QRect(10, 190, 31, 27))
        self.btnK.setAcceptDrops(False)
        self.btnK.setCheckable(True)
        self.btnK.setChecked(False)
        self.btnK.setAutoDefault(True)
        self.btnK.setDefault(False)
        self.btnK.setFlat(False)
        self.btnK.setObjectName(_fromUtf8("btnK"))
        self.btnG = QtGui.QPushButton(self.soundsGroup)
        self.btnG.setGeometry(QtCore.QRect(40, 190, 31, 27))
        self.btnG.setAcceptDrops(False)
        self.btnG.setCheckable(True)
        self.btnG.setChecked(False)
        self.btnG.setAutoDefault(True)
        self.btnG.setDefault(False)
        self.btnG.setFlat(False)
        self.btnG.setObjectName(_fromUtf8("btnG"))
        self.btnCH = QtGui.QPushButton(self.soundsGroup)
        self.btnCH.setGeometry(QtCore.QRect(70, 190, 31, 27))
        self.btnCH.setAcceptDrops(False)
        self.btnCH.setCheckable(True)
        self.btnCH.setChecked(False)
        self.btnCH.setAutoDefault(True)
        self.btnCH.setDefault(False)
        self.btnCH.setFlat(False)
        self.btnCH.setObjectName(_fromUtf8("btnCH"))
        self.btnJ = QtGui.QPushButton(self.soundsGroup)
        self.btnJ.setGeometry(QtCore.QRect(110, 190, 31, 27))
        self.btnJ.setAcceptDrops(False)
        self.btnJ.setCheckable(True)
        self.btnJ.setChecked(False)
        self.btnJ.setAutoDefault(True)
        self.btnJ.setDefault(False)
        self.btnJ.setFlat(False)
        self.btnJ.setObjectName(_fromUtf8("btnJ"))
        self.btnGN = QtGui.QPushButton(self.soundsGroup)
        self.btnGN.setGeometry(QtCore.QRect(140, 190, 31, 27))
        self.btnGN.setAcceptDrops(False)
        self.btnGN.setCheckable(True)
        self.btnGN.setChecked(False)
        self.btnGN.setAutoDefault(True)
        self.btnGN.setDefault(False)
        self.btnGN.setFlat(False)
        self.btnGN.setObjectName(_fromUtf8("btnGN"))
        self.lblPath = QtGui.QLabel(self.soundsGroup)
        self.lblPath.setGeometry(QtCore.QRect(0, 250, 511, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Consolas"))
        font.setPointSize(10)
        self.lblPath.setFont(font)
        self.lblPath.setFrameShape(QtGui.QFrame.Panel)
        self.lblPath.setFrameShadow(QtGui.QFrame.Raised)
        self.lblPath.setText(_fromUtf8(""))
        self.lblPath.setScaledContents(False)
        self.lblPath.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPath.setWordWrap(True)
        self.lblPath.setObjectName(_fromUtf8("lblPath"))
        self.lblCurrentFilepath = QtGui.QLabel(self.soundsGroup)
        self.lblCurrentFilepath.setGeometry(QtCore.QRect(10, 230, 461, 17))
        self.lblCurrentFilepath.setObjectName(_fromUtf8("lblCurrentFilepath"))
        self.btnPreview = QtGui.QPushButton(self.soundsGroup)
        self.btnPreview.setGeometry(QtCore.QRect(100, 300, 141, 31))
        self.btnPreview.setObjectName(_fromUtf8("btnPreview"))
        self.btnChangeFile = QtGui.QPushButton(self.soundsGroup)
        self.btnChangeFile.setGeometry(QtCore.QRect(270, 300, 141, 31))
        self.btnChangeFile.setObjectName(_fromUtf8("btnChangeFile"))
        self.btnSave = QtGui.QPushButton(Dialog)
        self.btnSave.setGeometry(QtCore.QRect(430, 360, 98, 27))
        self.btnSave.setObjectName(_fromUtf8("btnSave"))
        self.btnCancel = QtGui.QPushButton(Dialog)
        self.btnCancel.setGeometry(QtCore.QRect(320, 360, 98, 27))
        self.btnCancel.setObjectName(_fromUtf8("btnCancel"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.soundsGroup.setTitle(_translate("Dialog", "Modify Phoneme Sound Files", None))
        self.btnA.setText(_translate("Dialog", "a", None))
        self.btnO.setText(_translate("Dialog", "o", None))
        self.btnEU.setText(_translate("Dialog", "eu", None))
        self.btnE_grave.setText(_translate("Dialog", "è", None))
        self.btnE_acute.setText(_translate("Dialog", "é", None))
        self.btnE.setText(_translate("Dialog", "e", None))
        self.btnI.setText(_translate("Dialog", "i", None))
        self.btnU.setText(_translate("Dialog", "u", None))
        self.btnOU.setText(_translate("Dialog", "ou", None))
        self.btnAN.setText(_translate("Dialog", "an", None))
        self.btnON.setText(_translate("Dialog", "on", None))
        self.btnUN.setText(_translate("Dialog", "un", None))
        self.btnIN.setText(_translate("Dialog", "in", None))
        self.btnILL.setText(_translate("Dialog", "ill/y", None))
        self.btnUI.setText(_translate("Dialog", "ui", None))
        self.btnOI.setText(_translate("Dialog", "oi/w", None))
        self.btnP.setText(_translate("Dialog", "p", None))
        self.btnB.setText(_translate("Dialog", "b", None))
        self.btnF.setText(_translate("Dialog", "f", None))
        self.btnV.setText(_translate("Dialog", "v", None))
        self.btnM.setText(_translate("Dialog", "m", None))
        self.btnR.setText(_translate("Dialog", "r", None))
        self.btnT.setText(_translate("Dialog", "t", None))
        self.btnD.setText(_translate("Dialog", "d", None))
        self.btnS.setText(_translate("Dialog", "s", None))
        self.btnZ.setText(_translate("Dialog", "z", None))
        self.btnN.setText(_translate("Dialog", "n", None))
        self.btnL.setText(_translate("Dialog", "l", None))
        self.btnK.setText(_translate("Dialog", "k", None))
        self.btnG.setText(_translate("Dialog", "g", None))
        self.btnCH.setText(_translate("Dialog", "ch", None))
        self.btnJ.setText(_translate("Dialog", "j", None))
        self.btnGN.setText(_translate("Dialog", "gn", None))
        self.lblCurrentFilepath.setText(_translate("Dialog", "Current Filepath", None))
        self.btnPreview.setText(_translate("Dialog", "Preview Sound", None))
        self.btnChangeFile.setText(_translate("Dialog", "Change File", None))
        self.btnSave.setText(_translate("Dialog", "Save", None))
        self.btnCancel.setText(_translate("Dialog", "Cancel", None))

