/*
 * Generated by STIR. Do not edit by hand.
 */

#include <sifteo/asset.h>

#pragma once

extern Sifteo::AssetGroup BootAssets;
extern const Sifteo::AssetImage Bravo;
extern const Sifteo::AssetImage Grid;
extern const Sifteo::AssetImage Speaker;
extern const Sifteo::AssetImage Title;
extern const Sifteo::AssetImage LoadingBg;
extern Sifteo::AssetGroup IconAssets;
extern const Sifteo::AssetImage Icon;
