// THIS FILE IS GENERATED BY file_customizer.py DURING COMPILATION, DO NOT EDIT MANUALLY WITHOUT GREAT CAUTION

#include <sifteo.h>
#include "levels.gen.h"
#include "assets.gen.h"

const unsigned numLevels = 0;
const unsigned numSets = 0;

struct LevelSet Levels[numSets] = {};

struct Group LevelAssets[numSets] = {};

int setsInLevel[numLevels] = {};

unsigned failedAttemptsWeight = 50;
unsigned hintsRequestedWeight = 50;
unsigned timeWeight = 50;

